<template>
    <div class="row" style="max-width:100%">
        <div class="col-11 col-xl-9 mx-auto">
            <table class="mx-auto roundedz border border-primary text-light">
                <thead>
                <tr class="roundedz-top bg-primary ">
                    <th class="headerSort text-center" width="" tabindex="0" role="columnheader button" title="Sort ascending">Type</th>
                    <th class="headerSort text-center" data-sort-type="number" tabindex="0" role="columnheader button" title="Sort ascending">Name</th>
                    <th class="headerSort text-center" data-sort-type="number" tabindex="0" role="columnheader button" title="Sort ascending">Chance of<br>rarer <a class="text-light" href="https://wiki.guildwars2.com/wiki/Crafting_material" title="Crafting material">materials</a></th>
                    <th class="headerSort text-center" data-sort-type="number" tabindex="0" role="columnheader button" title="Sort ascending">Chance of<br>salvaging <a class="text-light" href="https://wiki.guildwars2.com/wiki/Upgrade_component" title="Upgrade component">upgrades</a></th>
                    <th class="headerSort text-center pe-2" data-sort-type="number" tabindex="0" role="columnheader button" title="Sort ascending">Cost</th>
                    <th class="headerSort text-center" data-sort-type="number" tabindex="0" role="columnheader button" title="Sort ascending">Uses</th>
                    <th class="headerSort text-center pe-2" data-sort-type="number" tabindex="0" role="columnheader button" title="Sort ascending">Cost/Use</th>
                    <th class="headerSort text-center" tabindex="0" role="columnheader button" title="Sort ascending">Usable on</th>
                </tr>
                </thead>
                <tbody>
                <tr class="text-center border-bottom border-primary">
                    <td class="border-end border-primary"><span class="small item-icon thumb-icon"><a href="https://wiki.guildwars2.com/wiki/Basic_Salvage_Kit" title="Basic Salvage Kit"><img alt="Basic Salvage Kit.png" src="https://wiki.guildwars2.com/images/d/d8/Basic_Salvage_Kit.png" decoding="async" width="64" height="64" style="vertical-align: bottom" data-file-width="64" data-file-height="64"></a></span></td>
                    <td class="border-end border-primary"><a href="https://wiki.guildwars2.com/wiki/Basic_Salvage_Kit" title="Basic Salvage Kit">Basic Salvage Kit</a></td>
                    <td class="border-end border-primary">10%</td>
                    <td class="border-end border-primary">20%</td>
                    <td class="border-end border-primary"><span class="price" style="white-space:nowrap;" data-sort-value="88">88&nbsp;<span style="position:relative; bottom:1px;"><a href="https://wiki.guildwars2.com/wiki/Coin" title="Copper coin"><img alt="Copper coin" src="https://wiki.guildwars2.com/images/thumb/e/eb/Copper_coin.png/20px-Copper_coin.png" decoding="async" width="20" height="16" srcset="/images/e/eb/Copper_coin.png 1.5x" data-file-width="29" data-file-height="23"></a></span></span><br><i>or</i> 77&nbsp;<span style="position:relative; bottom:2px;"><a href="https://wiki.guildwars2.com/wiki/Karma" title="Karma"><img alt="Karma.png" src="https://wiki.guildwars2.com/images/thumb/a/af/Karma.png/18px-Karma.png" decoding="async" width="18" height="14" srcset="/images/thumb/a/af/Karma.png/27px-Karma.png 1.5x, /images/thumb/a/af/Karma.png/36px-Karma.png 2x" data-file-width="63" data-file-height="48"></a></span></td>
                    <td class="border-end border-primary">25</td>
                    <td class="border-end border-primary">3.5&nbsp;<span style="position:relative; bottom:1px;"><a href="https://wiki.guildwars2.com/wiki/Coin" title="Copper coin"><img alt="Copper coin" src="https://wiki.guildwars2.com/images/thumb/e/eb/Copper_coin.png/20px-Copper_coin.png" decoding="async" width="20" height="16" srcset="/images/e/eb/Copper_coin.png 1.5x" data-file-width="29" data-file-height="23"></a></span><br><i>or</i> 3.1&nbsp;<span style="position:relative; bottom:2px;"><a href="https://wiki.guildwars2.com/wiki/Karma" title="Karma"><img alt="Karma.png" src="https://wiki.guildwars2.com/images/thumb/a/af/Karma.png/18px-Karma.png" decoding="async" width="18" height="14" srcset="/images/thumb/a/af/Karma.png/27px-Karma.png 1.5x, /images/thumb/a/af/Karma.png/36px-Karma.png 2x" data-file-width="63" data-file-height="48"></a></span></td>
                    <td class="border-primary"><b><span class="text-primary">Fine</span><br><span class="text-success">Masterwork</span></b></td>
                </tr>
                <tr class="text-center border-bottom border-primary">
                    <td class="border-end border-primary"> <span class="small item-icon thumb-icon"><a href="https://wiki.guildwars2.com/wiki/Copper-Fed_Salvage-o-Matic" title="Copper-Fed Salvage-o-Matic"><img alt="Copper-Fed Salvage-o-Matic.png" src="https://wiki.guildwars2.com/images/0/00/Copper-Fed_Salvage-o-Matic.png" decoding="async" width="64" height="64" style="vertical-align: bottom" data-file-width="64" data-file-height="64"></a></span></td>
                    <td class="border-end border-primary px-2"><a href="https://wiki.guildwars2.com/wiki/Copper-Fed_Salvage-o-Matic" title="Copper-Fed Salvage-o-Matic">Copper-Fed Salvage-o-Matic</a></td>
                    <td class="border-end border-primary">10%</td>
                    <td class="border-end border-primary">20%</td>
                    <td class="border-end border-primary">800&nbsp;<span style="position:relative; bottom:2px;"><a href="https://wiki.guildwars2.com/wiki/Gem" title="Gem"><img alt="Gem.png" src="https://wiki.guildwars2.com/images/thumb/a/aa/Gem.png/20px-Gem.png" decoding="async" width="20" height="18" srcset="/images/a/aa/Gem.png 1.5x" data-file-width="28" data-file-height="25"></a></span></td>
                    <td class="border-end border-primary">INF</td>
                    <td class="border-end border-primary">3&nbsp;<span style="position:relative; bottom:1px;"><a href="https://wiki.guildwars2.com/wiki/Coin" title="Copper coin"><img alt="Copper coin" src="https://wiki.guildwars2.com/images/thumb/e/eb/Copper_coin.png/20px-Copper_coin.png" decoding="async" width="20" height="16" srcset="/images/e/eb/Copper_coin.png 1.5x" data-file-width="29" data-file-height="23"></a></span></td>
                    <td class="border-primary"><b><span class="text-primary">Fine</span><br><span class="text-success">Masterwork</span></b></td>
                </tr>
                <tr class="text-center border-bottom border-primary">
                    <td class="border-end border-primary"> <span class="small item-icon thumb-icon"><a href="https://wiki.guildwars2.com/wiki/Mystic_Salvage_Kit" title="Mystic Salvage Kit"><img alt="Mystic Salvage Kit.png" src="https://wiki.guildwars2.com/images/0/0e/Mystic_Salvage_Kit.png" decoding="async" width="64" height="64" style="vertical-align: bottom" data-file-width="64" data-file-height="64"></a></span></td>
                    <td class="border-end border-primary"><a href="https://wiki.guildwars2.com/wiki/Mystic_Salvage_Kit" title="Mystic Salvage Kit">Mystic Salvage Kit</a></td>
                    <td class="border-end border-primary">25%</td>
                    <td class="border-end border-primary">80%</td>
                    <td class="border-end border-primary"><span class="price" style="white-space:nowrap;" data-sort-value="2624"> 26&nbsp;<span style="position:relative;"><a href="https://wiki.guildwars2.com/wiki/Coin" title="Silver coin"><img alt="Silver coin" src="https://wiki.guildwars2.com/images/thumb/3/3c/Silver_coin.png/20px-Silver_coin.png" decoding="async" width="20" height="20" srcset="/images/thumb/3/3c/Silver_coin.png/30px-Silver_coin.png 1.5x, /images/3/3c/Silver_coin.png 2x" data-file-width="32" data-file-height="32"></a></span></span>24&nbsp;<span style="position:relative; bottom:1px;"><a href="https://wiki.guildwars2.com/wiki/Coin" title="Copper coin"><img alt="Copper coin" src="https://wiki.guildwars2.com/images/thumb/e/eb/Copper_coin.png/20px-Copper_coin.png" decoding="async" width="20" height="16" srcset="/images/e/eb/Copper_coin.png 1.5x" data-file-width="29" data-file-height="23"></a></span><i>+</i> 3 <a href="https://wiki.guildwars2.com/wiki/Mystic_Forge_Stone" title="Mystic Forge Stone"><img alt="Mystic Forge Stone.png" src="https://wiki.guildwars2.com/images/thumb/3/34/Mystic_Forge_Stone.png/16px-Mystic_Forge_Stone.png" decoding="async" width="16" height="16" srcset="/images/thumb/3/34/Mystic_Forge_Stone.png/24px-Mystic_Forge_Stone.png 1.5x, /images/thumb/3/34/Mystic_Forge_Stone.png/32px-Mystic_Forge_Stone.png 2x" data-file-width="64" data-file-height="64"></a><sup id="cite_ref-Mystic_Forge_Stone_2-0" class="reference"><a href="#cite_note-Mystic_Forge_Stone-2"></a></sup> <br><i>or</i> 8,652&nbsp;<span style="position:relative; bottom:2px;"><a href="https://wiki.guildwars2.com/wiki/Karma" title="Karma"><img alt="Karma.png" src="https://wiki.guildwars2.com/images/thumb/a/af/Karma.png/18px-Karma.png" decoding="async" width="18" height="14" srcset="/images/thumb/a/af/Karma.png/27px-Karma.png 1.5x, /images/thumb/a/af/Karma.png/36px-Karma.png 2x" data-file-width="63" data-file-height="48"></a></span> <i>+</i> 3 <a href="https://wiki.guildwars2.com/wiki/Mystic_Forge_Stone" title="Mystic Forge Stone"><img alt="Mystic Forge Stone.png" src="https://wiki.guildwars2.com/images/thumb/3/34/Mystic_Forge_Stone.png/16px-Mystic_Forge_Stone.png" decoding="async" width="16" height="16" srcset="/images/thumb/3/34/Mystic_Forge_Stone.png/24px-Mystic_Forge_Stone.png 1.5x, /images/thumb/3/34/Mystic_Forge_Stone.png/32px-Mystic_Forge_Stone.png 2x" data-file-width="64" data-file-height="64"></a><sup id="cite_ref-Mystic_Forge_Stone_2-1" class="reference"><a href="#cite_note-Mystic_Forge_Stone-2"></a></sup></td>
                    <td class="border-end border-primary">250</td>
                    <td class="border-end border-primary">10.5&nbsp;<span style="position:relative; bottom:1px;"><a href="https://wiki.guildwars2.com/wiki/Coin" title="Copper coin"><img alt="Copper coin" src="https://wiki.guildwars2.com/images/thumb/e/eb/Copper_coin.png/20px-Copper_coin.png" decoding="async" width="20" height="16" srcset="/images/e/eb/Copper_coin.png 1.5x" data-file-width="29" data-file-height="23"></a></span><sup id="cite_ref-Variable_extra_cost_3-0" class="reference"><a href="#cite_note-Variable_extra_cost-3"></a></sup><br><i>or</i> 34.6&nbsp;<span style="position:relative; bottom:2px;"><a href="https://wiki.guildwars2.com/wiki/Karma" title="Karma"><img alt="Karma.png" src="https://wiki.guildwars2.com/images/thumb/a/af/Karma.png/18px-Karma.png" decoding="async" width="18" height="14" srcset="/images/thumb/a/af/Karma.png/27px-Karma.png 1.5x, /images/thumb/a/af/Karma.png/36px-Karma.png 2x" data-file-width="63" data-file-height="48"></a></span><sup id="cite_ref-Variable_extra_cost_3-1" class="reference"><a href="#cite_note-Variable_extra_cost-3" title=""></a></sup></td>
                    <td class="border-primary"><b><span class="text-warning">Rare</span><br><span class="text-orange">Exotic</span></b></td>
                </tr>
                <tr class="text-center border-bottom border-primary">
                    <td class="border-end border-primary"> <span class="small item-icon thumb-icon"><a href="https://wiki.guildwars2.com/wiki/Black_Lion_Salvage_Kit" title="Black Lion Salvage Kit"><img alt="Black Lion Salvage Kit.png" src="https://wiki.guildwars2.com/images/1/1d/Black_Lion_Salvage_Kit.png" decoding="async" width="64" height="64" style="vertical-align: bottom" data-file-width="64" data-file-height="64"></a></span></td>
                    <td class="border-end border-primary"><a href="https://wiki.guildwars2.com/wiki/Black_Lion_Salvage_Kit" title="Black Lion Salvage Kit">Black Lion Salvage Kit</a></td>
                    <td class="border-end border-primary">50%</td>
                    <td class="border-end border-primary">100%</td>
                    <td class="border-end border-primary">300&nbsp;<span style="position:relative; bottom:2px;"><a href="https://wiki.guildwars2.com/wiki/Gem" title="Gem"><img alt="Gem.png" src="https://wiki.guildwars2.com/images/thumb/a/aa/Gem.png/20px-Gem.png" decoding="async" width="20" height="18" srcset="/images/a/aa/Gem.png 1.5x" data-file-width="28" data-file-height="25"></a></span></td>
                    <td class="border-end border-primary">25</td>
                    <td class="border-end border-primary">12&nbsp;<span style="position:relative; bottom:2px;"><a href="https://wiki.guildwars2.com/wiki/Gem" title="Gem"><img alt="Gem.png" src="https://wiki.guildwars2.com/images/thumb/a/aa/Gem.png/20px-Gem.png" decoding="async" width="20" height="18" srcset="/images/a/aa/Gem.png 1.5x" data-file-width="28" data-file-height="25"></a></span></td>
                    <td class="border-primary"><b><span class="text-warning">Rare</span><br><span class="text-orange">Exotic</span></b></td>
                </tr>
                <tr class="text-center border-bottom border-primary">
                    <td class="border-end border-primary"> <span class="small item-icon thumb-icon"><a href="https://wiki.guildwars2.com/wiki/Ascended_Salvage_Tool" title="Ascended Salvage Tool"><img alt="Ascended Salvage Tool.png" src="https://wiki.guildwars2.com/images/d/d7/Ascended_Salvage_Tool.png" decoding="async" width="64" height="64" style="vertical-align: bottom" data-file-width="64" data-file-height="64"></a></span></td>
                    <td class="border-end border-primary"><a href="https://wiki.guildwars2.com/wiki/Ascended_Salvage_Tool" title="Ascended Salvage Tool">Ascended Salvage (Any)</a></td>
                    <td class="border-end border-primary">?%</td>
                    <td class="border-end border-primary">100%</td>
                    <td class="border-end border-primary">2&nbsp;<a href="https://wiki.guildwars2.com/wiki/Fractal_Relic" title="Fractal Relics"><img alt="Fractal Relics" src="https://wiki.guildwars2.com/images/thumb/5/57/Fractal_Relic.png/20px-Fractal_Relic.png" decoding="async" width="20" height="20" srcset="/images/thumb/5/57/Fractal_Relic.png/30px-Fractal_Relic.png 1.5x, /images/thumb/5/57/Fractal_Relic.png/40px-Fractal_Relic.png 2x" data-file-width="64" data-file-height="64"></a>+1&nbsp;<span style="position:relative;"><a href="https://wiki.guildwars2.com/wiki/Coin" title="Gold coin"><img alt="Gold coin" src="https://wiki.guildwars2.com/images/thumb/d/d1/Gold_coin.png/20px-Gold_coin.png" decoding="async" width="20" height="20" srcset="/images/thumb/d/d1/Gold_coin.png/30px-Gold_coin.png 1.5x, /images/d/d1/Gold_coin.png 2x" data-file-width="32" data-file-height="32"></a></span><br><i>or</i> 1<span style="position:relative; bottom:1px;"><a href="https://wiki.guildwars2.com/wiki/Laurel" title="Laurel"><img alt="Laurel.png" src="https://wiki.guildwars2.com/images/thumb/5/56/Laurel.png/20px-Laurel.png" decoding="async" width="20" height="20" srcset="/images/thumb/5/56/Laurel.png/30px-Laurel.png 1.5x, /images/thumb/5/56/Laurel.png/40px-Laurel.png 2x" data-file-width="65" data-file-height="65"></a></span>+1&nbsp;<span style="position:relative;"><a href="https://wiki.guildwars2.com/wiki/Coin" title="Gold coin"><img alt="Gold coin" src="https://wiki.guildwars2.com/images/thumb/d/d1/Gold_coin.png/20px-Gold_coin.png" decoding="async" width="20" height="20" srcset="/images/thumb/d/d1/Gold_coin.png/30px-Gold_coin.png 1.5x, /images/d/d1/Gold_coin.png 2x" data-file-width="32" data-file-height="32"></a></span></td>
                    <td class="border-end border-primary">1</td>
                    <td class="border-end border-primary">2&nbsp;<a href="https://wiki.guildwars2.com/wiki/Fractal_Relic" title="Fractal Relics"><img alt="Fractal Relics" src="https://wiki.guildwars2.com/images/thumb/5/57/Fractal_Relic.png/20px-Fractal_Relic.png" decoding="async" width="20" height="20" srcset="/images/thumb/5/57/Fractal_Relic.png/30px-Fractal_Relic.png 1.5x, /images/thumb/5/57/Fractal_Relic.png/40px-Fractal_Relic.png 2x" data-file-width="64" data-file-height="64"></a>+1&nbsp;<span style="position:relative;"><a href="https://wiki.guildwars2.com/wiki/Coin" title="Gold coin"><img alt="Gold coin" src="https://wiki.guildwars2.com/images/thumb/d/d1/Gold_coin.png/20px-Gold_coin.png" decoding="async" width="20" height="20" srcset="/images/thumb/d/d1/Gold_coin.png/30px-Gold_coin.png 1.5x, /images/d/d1/Gold_coin.png 2x" data-file-width="32" data-file-height="32"></a></span><br><i>or</i> 1<span style="position:relative; bottom:1px;"><a href="https://wiki.guildwars2.com/wiki/Laurel" title="Laurel"><img alt="Laurel.png" src="https://wiki.guildwars2.com/images/thumb/5/56/Laurel.png/20px-Laurel.png" decoding="async" width="20" height="20" srcset="/images/thumb/5/56/Laurel.png/30px-Laurel.png 1.5x, /images/thumb/5/56/Laurel.png/40px-Laurel.png 2x" data-file-width="65" data-file-height="65"></a></span>+1&nbsp;<span style="position:relative;"><a href="https://wiki.guildwars2.com/wiki/Coin" title="Gold coin"><img alt="Gold coin" src="https://wiki.guildwars2.com/images/thumb/d/d1/Gold_coin.png/20px-Gold_coin.png" decoding="async" width="20" height="20" srcset="/images/thumb/d/d1/Gold_coin.png/30px-Gold_coin.png 1.5x, /images/d/d1/Gold_coin.png 2x" data-file-width="32" data-file-height="32"></a></span></td>
                    <td class="border-primary"><a href="https://wiki.guildwars2.com/wiki/Ascended_equipment" title="Ascended equipment"><span class="text-pink"><b>Ascended</b></span></a></td>
                </tr>
                <tr class="text-center border-bottom border-primary">
                    <td class="border-end border-primary"> <span class="small item-icon thumb-icon"><a href="https://wiki.guildwars2.com/wiki/Portable_Composter" title="Portable Composter"><img alt="Portable Composter.png" src="https://wiki.guildwars2.com/images/9/9a/Portable_Composter.png" decoding="async" width="64" height="64" style="vertical-align: bottom" data-file-width="64" data-file-height="64"></a></span></td>
                    <td class="border-end border-primary"><a href="https://wiki.guildwars2.com/wiki/Portable_Composter" title="Portable Composter">Portable Composter</a></td>
                    <td class="border-end border-primary">?%</td>
                    <td class="border-end border-primary">n/a</td>
                    <td class="border-end border-primary">4 <a href="https://wiki.guildwars2.com/wiki/Spiritwood_Plank" title="Spiritwood Plank"><img alt="Spiritwood Plank.png" src="https://wiki.guildwars2.com/images/thumb/8/8e/Spiritwood_Plank.png/16px-Spiritwood_Plank.png" decoding="async" width="16" height="16" srcset="/images/thumb/8/8e/Spiritwood_Plank.png/24px-Spiritwood_Plank.png 1.5x, /images/thumb/8/8e/Spiritwood_Plank.png/32px-Spiritwood_Plank.png 2x" data-file-width="64" data-file-height="64"></a> + <a href="https://wiki.guildwars2.com/wiki/Elonian_Leather_Square" title="Elonian Leather Square"><img alt="Elonian Leather Square.png" src="https://wiki.guildwars2.com/images/thumb/a/a2/Elonian_Leather_Square.png/16px-Elonian_Leather_Square.png" decoding="async" width="16" height="16" srcset="/images/thumb/a/a2/Elonian_Leather_Square.png/24px-Elonian_Leather_Square.png 1.5x, /images/thumb/a/a2/Elonian_Leather_Square.png/32px-Elonian_Leather_Square.png 2x" data-file-width="64" data-file-height="64"></a> <sup id="cite_ref-Portal_Composter_6-0" class="reference"><a href="#cite_note-Portal_Composter-6" title=""></a></sup></td>
                    <td class="border-end border-primary">INF</td>
                    <td class="border-end border-primary">Free</td>
                    <td class="border-primary"><a href="https://wiki.guildwars2.com/wiki/Food" title="Food"><b>Foods</b></a> <br> <a href="https://wiki.guildwars2.com/wiki/Feast" title="Feast"><b>Feasts</b></a></td>
                </tr>
                <tr class="text-center border-bottom border-primary">
                    <td class="border-end border-primary"> <span class="small item-icon thumb-icon"><a href="https://wiki.guildwars2.com/wiki/Research_Kit" title="Research Kit"><img alt="Research Kit.png" src="https://wiki.guildwars2.com/images/1/12/Research_Kit.png" decoding="async" width="64" height="64" style="vertical-align: bottom" data-file-width="64" data-file-height="64"></a></span></td>
                    <td class="border-end border-primary"><a href="https://wiki.guildwars2.com/wiki/Research_Kit" title="Research Kit">Research Kit</a></td>
                    <td class="border-end border-primary">?%</td>
                    <td class="border-end border-primary">n/a</td>
                    <td class="border-end border-primary">2&nbsp;<span style="position:relative;"><a href="https://wiki.guildwars2.com/wiki/Coin" title="Silver coin"><img alt="Silver coin" src="https://wiki.guildwars2.com/images/thumb/3/3c/Silver_coin.png/20px-Silver_coin.png" decoding="async" width="20" height="20" srcset="/images/thumb/3/3c/Silver_coin.png/30px-Silver_coin.png 1.5x, /images/3/3c/Silver_coin.png 2x" data-file-width="32" data-file-height="32"></a></span></td>
                    <td class="border-end border-primary">250</td>
                    <td class="border-end border-primary">0.8&nbsp;<span style="position:relative; bottom:1px;"><a href="https://wiki.guildwars2.com/wiki/Coin" title="Copper coin"><img alt="Copper coin" src="https://wiki.guildwars2.com/images/thumb/e/eb/Copper_coin.png/20px-Copper_coin.png" decoding="async" width="20" height="16" srcset="/images/e/eb/Copper_coin.png 1.5x" data-file-width="29" data-file-height="23"></a></span></td>
                    <td class="border-primary px-2"><a href="https://wiki.guildwars2.com/wiki/Crafting" title="Crafting"><b>Crafted Items</b></a></td>
                </tr>
                </tbody>
                <tfoot></tfoot>
            </table>
        </div>
    </div>
    <div class="col-11 mx-auto text-center text-success fw-bold pt-2">
        This is a list of best to pick salvage kits.
    </div>
</template>
<script>
export default {
    name: 'salvage_view',
    data(){
        return{
        }
    },
    methods:{

    }
}
</script>
<style scoped>

</style>